before:
  hooks:
    - go mod tidy

builds:
- env:
  - CGO_ENABLED=0
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - 386
    - arm
    - arm64

  ignore:
    - goos: darwin
      goarch: '386'
    - goos: windows
      goarch: 'arm'
    - goos: windows
      goarch: 'arm64'

  ldflags:
    - -s -w

  binary: '{{ .ProjectName }}'
  main: cmd/dict/main.go

upx:
  -
    ids: [ default ]
    enabled: true
    goos: ["windows", "linux"]
    goarch: ["amd64", "386"]
    compress: best
#    lzma: true
#    brute: true
archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'

checksum:
  algorithm: sha256