name: 🎉 Release Binary

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: "Check out code 1"
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      
      - name: "Set up Go"
        uses: actions/setup-go@v4
        with: 
          go-version: 1.21.x

      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: UPX version
        run: upx --version

      - name: "Create release on GitHub"
        uses: goreleaser/goreleaser-action@v4
        with: 
          args: "release --clean"
          version: latest
          workdir: .
        env: 
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"